[package]
name = "cairo_matrix"
version = "0.1.0"
edition = "2023_11"
homepage= "https://github.com/cairo-math/cairo-matrix"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]